import { CopySnippet } from "@/components/copy-snippet";
import { PackageTabs } from "@/components/package-tabs";
import { getPackage } from "@/lib/api";
import { Badge, StatCard } from "@private-pub/ui";
import { Box, CheckCircle2, Clock3, Download, ExternalLink, GitBranch, ShieldCheck } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

export async function generateMetadata({ params }: { params: Promise<{ name: string }> }): Promise<Metadata> { const { name } = await params; return { title: name }; }

export default async function PackagePage({ params, searchParams }: { params: Promise<{ name: string }>; searchParams: Promise<{ tab?: string }> }) {
  const { name } = await params; const { tab = "readme" } = await searchParams;
  const detail = await getPackage(name); if (!detail) notFound();
  return <main className="package-page">
    <section className="package-hero"><div className="content-shell"><div className="breadcrumbs"><Link href="/">Packages</Link><span>/</span><strong>{name}</strong></div><div className="package-title-row"><div className="big-package-icon"><Box /></div><div className="package-title"><div><h1>{name}</h1><Badge tone="blue">v{detail.package.latestVersion}</Badge><Badge tone="green">Stable</Badge></div><p>{detail.package.description}</p><div className="package-meta"><span><CheckCircle2 size={15} />Published by <Link href={`/publishers/${detail.package.publisherId}`}>{detail.package.publisherId}</Link></span><span><Clock3 size={15} />Updated 1 day ago</span></div></div><div className="package-actions"><button><GitBranch size={16} />Repository</button><button><ExternalLink size={16} />Documentation</button></div></div></div></section>
    <div className="content-shell"><PackageTabs name={name} active={tab} /><div className="detail-layout"><section className="detail-main">
      {tab === "versions" ? <Versions detail={detail} name={name} /> : tab === "scores" ? <Scores detail={detail} /> : tab === "admin" ? <PackageAdmin name={name} /> : <Document title={tab === "changelog" ? "Changelog" : "About this package"} text={tab === "changelog" ? detail.changelog : detail.readme} />}
    </section><aside className="package-sidebar"><div className="side-card"><span className="eyebrow">Install</span><h3>Add to pubspec.yaml</h3><CopySnippet>{`${name}: ^${detail.package.latestVersion}`}</CopySnippet><a href="/tokens">Configure private registry →</a></div><div className="side-card"><span className="eyebrow">Package metadata</span><dl><dt>License</dt><dd>MIT</dd><dt>SDK</dt><dd>Flutter</dd><dt>Platforms</dt><dd>{detail.latestVersion.platforms.join(", ")}</dd><dt>Archive</dt><dd>{detail.latestVersion.archiveSha256.slice(0, 10)}…</dd></dl></div><div className="side-card security"><ShieldCheck /><div><strong>Supply-chain verified</strong><p>Archive integrity checked and analysis completed.</p></div></div></aside></div></div>
  </main>;
}

function Document({ title, text }: { title: string; text: string }) { return <article className="readme"><span className="eyebrow">Documentation</span><h2>{title}</h2>{text.split("\n").map((line, i) => line.startsWith("# ") ? <h1 key={i}>{line.slice(2)}</h1> : line.startsWith("## ") ? <h2 key={i}>{line.slice(3)}</h2> : line.startsWith("- ") ? <li key={i}>{line.slice(2)}</li> : line ? <p key={i}>{line}</p> : <br key={i} />)}</article>; }
function Versions({ detail, name }: { detail: NonNullable<Awaited<ReturnType<typeof getPackage>>>; name: string }) { return <div className="table-card"><div className="table-title"><div><span className="eyebrow">Release history</span><h2>Versions</h2></div><Badge>{detail.versions.length} releases</Badge></div><div className="table-scroll"><table><thead><tr><th>Version</th><th>Published</th><th>Min SDK</th><th>Source</th><th>Actions</th></tr></thead><tbody>{detail.versions.map((v) => <tr key={v.version}><td><strong>{v.version}</strong>{v.prerelease && <Badge tone="amber">Pre</Badge>}</td><td>{new Date(v.publishedAt).toLocaleDateString()}</td><td>{v.sdk.dart.split(" ")[0]}</td><td>{v.sourceType === "native" ? "Native publish" : "pub.dev import"}</td><td><Link href={`/packages/${name}/files?version=${v.version}`}>Browse files</Link> <Download size={14} /></td></tr>)}</tbody></table></div></div>; }
function Scores({ detail }: { detail: NonNullable<Awaited<ReturnType<typeof getPackage>>> }) { return <div><div className="score-grid"><StatCard label="Pub points" value={`${detail.score.grantedPoints}/${detail.score.maxPoints}`} detail="Automated quality checks" accent="blue" /><StatCard label="Popularity" value={`${Math.round(detail.score.popularityScore * 100)}%`} detail="Internal usage signal" accent="purple" /><StatCard label="Maintenance" value={`${Math.round(detail.score.maintenanceScore * 100)}%`} detail="Release and dependency health" accent="green" /></div><div className="score-breakdown"><div className="table-title"><div><span className="eyebrow">Detailed analysis</span><h2>Score breakdown</h2></div></div>{detail.score.breakdown.map((item) => <div className="score-row" key={item.label}><span className={`score-status ${item.status}`} /><div><strong>{item.label}</strong><small>{item.status === "pass" ? "All checks passed" : "Improvements available"}</small></div><div className="score-bar"><i style={{ width: `${item.points / item.max * 100}%` }} /></div><b>{item.points}/{item.max}</b></div>)}</div></div>; }
function PackageAdmin({ name }: { name: string }) { return <div className="admin-package"><span className="eyebrow">Package controls</span><h2>Administration</h2><p>High-impact actions are protected by package-admin permissions and recorded in the audit log.</p><div className="danger-row"><div><strong>Recompute analysis</strong><p>Queue a fresh analysis and score run.</p></div><button>Queue analysis</button></div><div className="danger-row"><div><strong>Discontinue {name}</strong><p>Keep versions available while directing users to a replacement.</p></div><button className="danger">Discontinue</button></div></div>; }
