"use client";
import { Badge } from "@private-pub/ui";
import { CheckCircle2, CloudDownload, Loader2, PackageSearch } from "lucide-react";
import { useState } from "react";

export default function ImportsPage() {
  const [status, setStatus] = useState("Ready to validate a package from pub.dev.");
  const [loading, setLoading] = useState(false);
  async function submit(formData: FormData) { setLoading(true); const name = String(formData.get("packageName") ?? ""); const versions = String(formData.get("versions") ?? "").split(",").map((v) => v.trim()).filter(Boolean); await new Promise((r) => setTimeout(r, 650)); setStatus(`Job queued for ${name} (${versions.join(", ")}). Worker will verify provenance and index files.`); setLoading(false); }
  return <main className="subpage"><div className="content-shell compact-content"><div className="page-heading"><div><span className="eyebrow">Supply packages</span><h1>Import from pub.dev</h1><p>Create a trusted internal snapshot while preserving source provenance.</p></div><Badge tone="blue"><CloudDownload size={13} />Controlled import</Badge></div><div className="wizard"><div className="wizard-steps"><span className="active">1 <i>Source</i></span><b /><span>2 <i>Validate</i></span><b /><span>3 <i>Import</i></span><b /><span>4 <i>Result</i></span></div><form action={submit}><div className="form-grid"><label>Package name<input name="packageName" defaultValue="archive" required pattern="[a-z][a-z0-9_]*" /></label><label>Import mode<select name="mode"><option>snapshot</option><option>mirror</option><option>sealed</option></select></label></div><label>Versions<input name="versions" defaultValue="4.0.8, 4.0.9" required /></label><fieldset className="check-grid"><label><input type="checkbox" defaultChecked />Verify archive SHA256</label><label><input type="checkbox" defaultChecked />Create file index</label><label><input type="checkbox" defaultChecked />Import score snapshot</label><label><input type="checkbox" defaultChecked />Generate previews</label></fieldset><div className="validation-box"><PackageSearch /><div><strong>Import readiness</strong><p>{status}</p></div></div><div className="form-actions"><button type="button">Validate only</button><button className="primary" disabled={loading}>{loading ? <Loader2 className="spin" /> : <CheckCircle2 />}Start import</button></div></form></div></div></main>;
}
